<a href="https://colab.research.google.com/github/aayrm5/Zero_to_GANS/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1wAIsWYLVLy18ZSXGjaA7ZakRqJmTvUA8')

     |████████████████████████████████| 71kB 3.2MB/s 


# PyTorch functions for operations on tensors

An short introduction about PyTorch and about the chosen functions. 

- torch.from_numpy
- torch.complex
- torch.hstack
- tensor.narrow
- torch.transpose

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

In [3]:
import numpy as np



# This is formatted as code

## Function 1 - torch.from_numpy

Creates a Tensor from a numpy.ndarray. The returned tensor and ndarray share the same memory. Modifications to the tensor will be reflected in the ndarray and vice versa. The returned tensor is not resizable.

In [5]:
# Example 1 - working 
arr = np.array([[1,2,3],[5,6,7]])

ten = torch.from_numpy(arr)
print(ten)
print(ten.dtype)

tensor([[1, 2, 3],
        [5, 6, 7]])
torch.int64


The above example shows how a 2D numpy array has been converted to tensor of int64.

In [10]:
# Example 2 - working
arr1 = np.random.randn(5,5)
print(arr1)
print(arr1.dtype)

t1 = torch.from_numpy(arr1)
print(t1)
print(t1.dtype)

[[-0.47933258 -0.93466813 -0.88072474  0.29290626 -0.98801339]
 [ 0.06330733  0.51426056  0.9141022   0.39718783 -1.62442852]
 [-0.7000188  -0.94014641  0.04239408  0.48902126 -0.35258211]
 [-1.22310722  0.93022085  1.59484913  0.64926354  0.01355259]
 [-0.14499633 -0.25924037 -0.05237166 -1.46272417 -0.47922014]]
float64
tensor([[-0.4793, -0.9347, -0.8807,  0.2929, -0.9880],
        [ 0.0633,  0.5143,  0.9141,  0.3972, -1.6244],
        [-0.7000, -0.9401,  0.0424,  0.4890, -0.3526],
        [-1.2231,  0.9302,  1.5948,  0.6493,  0.0136],
        [-0.1450, -0.2592, -0.0524, -1.4627, -0.4792]], dtype=torch.float64)
torch.float64


Example 2 shows how numpy array of shape 5x5 is transformed into tensor of same float64 data type.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = np.array([[1,2,3],['a','b','c']])
print(arr2.dtype)

t3 = torch.from_numpy(arr2)

<U21


TypeError: ignored

The array, arr2 has datatypes strings in one of the sub arrays. This is not supported by the tensors. As mentioned in the error, the only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

Closing comments about when to use this function:

You could use the from_numpy function when you want to convert an numpy array into a tensor, given you respect the tensor restrictions.

Let's save our work using Jovian before continuing.

In [13]:
!pip install jovian --upgrade --quiet

In [14]:
import jovian

In [15]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aayrm5/01-tensor-operations


'https://jovian.ai/aayrm5/01-tensor-operations'

## Function 2 - torch.complex

Constructs a complex tensor with its real part equal to real and it's imaginary part equal to imag. Takes two tensors as input and outs one complex tensor.

In [16]:
# Example 1 - working
real = torch.tensor([1,2], dtype = torch.float32)
imag = torch.tensor([3,4], dtype=torch.float32)

z = torch.complex(real,imag)
print(z.dtype)
print(z)

torch.complex64
tensor([1.+3.j, 2.+4.j])


The above example shows how to contruct a complex tensor by joining a real and imaginaroy part of tensors.
Note that, when real and imag are of data type float32 the output has a complex of datatype complex64.

In [20]:
# Example 2 - working
real = torch.tensor([[1,2,3],[7,8,9]], dtype = torch.float64)
imag = torch.tensor([[11,12,13],[87,89,7878]], dtype = torch.float64)

z = torch.complex(real, imag)
print(z)
print(z.dtype)

tensor([[1.+11.j, 2.+12.j, 3.+13.j],
        [7.+87.j, 8.+89.j, 9.+7878.j]], dtype=torch.complex128)
torch.complex128


The above example shows that complex accepts real and imag with same dtype. Also now that the dtype are of float64, the output complex has a datatype of complex128.



In [21]:
# Example 3 - breaking (to illustrate when it breaks)
real = torch.tensor([[1,2,3],[7,8,9]], dtype = torch.int64)
imag = torch.tensor([[11,12,13],[87,89,7878]], dtype = torch.int64)

z = torch.complex(real, imag)
print(z)
print(z.dtype)

RuntimeError: ignored

The torch.complex function only accepts real and imag tensors with datatypes of float or double and both of them should have similar datatypes for it to function.

Closing comments about when to use this function:

torch.complex function is really useful in building complex equation real quick. Just keep in mind the limitations of this function.

In [22]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aayrm5/01-tensor-operations


'https://jovian.ai/aayrm5/01-tensor-operations'

## Function 3 - torch.hstack

The above function helps stack tensors in sequence horizontally (column wise). Takes multiple tensors as input and returns one concatanated tensor as output.

In [26]:
# Example 1 - working
t1 = torch.tensor([1, 2, 3, 5, 6])
print(t1.dtype, end='\n\n')
t2 = torch.tensor([4, 5, 6, 7, 8])
print(t2.dtype, end='\n\n')

t3 = torch.hstack((t1,t2))
print(t3)
print(t3.dtype)

torch.int64

torch.int64

tensor([1, 2, 3, 5, 6, 4, 5, 6, 7, 8])
torch.int64


Explanation about example1:
- t3 is a result of horizontal contactination of two tensors t1 & t2. The datatype remained same as t1 & t2.

In [33]:
# Example 2 - working
t1 = torch.tensor([[1.5],[2.5],[3.5]])
print(t1.dtype, t1.shape, end='\n\n')
t2 = torch.tensor([[4],[5],[6]])
print(t2.dtype, t2.shape, end='\n\n')
t3 = torch.hstack((t1,t2))
print(t3)
print(t3.dtype, t3.shape)

torch.float32 torch.Size([3, 1])

torch.int64 torch.Size([3, 1])

tensor([[1.5000, 4.0000],
        [2.5000, 5.0000],
        [3.5000, 6.0000]])
torch.float32 torch.Size([3, 2])


Explanation about example:
- This example has two tensors with same size of [3,1] but with different datatypes of float32 and int64, the resultant tensor has a datatype of float32 as the entire tensor has been converted into suitable, one datatype.

In [34]:
# Example 3 - breaking (to illustrate when it breaks)

t1 = torch.tensor([[1.5],[2.5],[3.5]])
print(t1.dtype, t1.shape, end='\n\n')
t2 = torch.tensor([[4],[5]])
print(t2.dtype, t2.shape, end='\n\n')
t3 = torch.hstack((t1,t2))
print(t3)
print(t3.dtype, t3.shape)


torch.float32 torch.Size([3, 1])

torch.int64 torch.Size([2, 1])



RuntimeError: ignored

Explanation about example:
- passing tensors with different dimensions to the hstack function breaks it.
- As the error suggests, sizes of tensors must match for it to work.

Closing comments about when to use this function:
- tensor.hstack function comes in handy when you want to join multiple tensors, just be cautious about their datatypes and shape. Remember to pass in tensors of same dtype as arguements.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - tensor.narrow

This function returns a new tensor that is a narrowed version of input tensor. Takes multiple arguments such as input, dim, start, length. The returned tensor and the input tensor share the same memory.

In [38]:
# Example 1 - working
t4 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(t4)

nar_0 = torch.narrow(t4, 0, 1, 2)
print(nar_0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[4, 5, 6],
        [7, 8, 9]])


Explanation about example:
- The above function extracts a subset of the tensor t4 by starting at index 1, dimention 0 (specifies rows) and the length of 2 which grabs 2 rows out of 3.

In [40]:
# Example 2 - working
print(t4)

nar_1 = torch.narrow(t4, 1, 0, 2)
print(nar_1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2],
        [4, 5],
        [7, 8]])


Explanation about example:
- The above function has been sliced vertically when you pass a dimention 1, it is starting at 0 index for columns and grabs 2 of them.

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
print(t4)

nar_1 = torch.narrow(t4, 1, 0, 4)
print(nar_1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


RuntimeError: ignored

Explanation about example:
 - touch.narrow function breaks when you pass the dimension greater than the dimension of the input tensor.

Closing comments about when to use this function:
- touch.narrow function is helpful in subsetting tensors and having multiple inputs makes it easier to mention the shape and size of the subset tensor.

In [42]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aayrm5/01-tensor-operations


'https://jovian.ai/aayrm5/01-tensor-operations'

## Function 5 - torch.transpose

The above function returns a tensor that is a transposed version of input. This function accpets parameters as input, dim0, and dim1. The given dimensions dim0 & dim1 are swapped.

In [50]:
# Example 1 - working
tt1 = torch.randn(5,3)
print(tt1)

tran1 = torch.transpose(tt1, 0, 1)
print(tran1)

tensor([[-0.3004,  0.1901,  2.3058],
        [ 1.0754, -0.4700, -0.8900],
        [ 0.1029,  0.1087,  0.3508],
        [ 0.1336,  2.5423,  1.5134],
        [ 1.2471, -0.0053, -0.3461]])
tensor([[-0.3004,  1.0754,  0.1029,  0.1336,  1.2471],
        [ 0.1901, -0.4700,  0.1087,  2.5423, -0.0053],
        [ 2.3058, -0.8900,  0.3508,  1.5134, -0.3461]])


Explanation about example:
- The above function transposed the tensor of size [5,3] to a tensor of size [3,5]. 0, 1 in the above example denotes that they'd be transposed.

In [52]:
# Example 2 - working
print(tt1)

tran2 = torch.transpose(tt1, 1, 0)
print(tran2)

tensor([[-0.3004,  0.1901,  2.3058],
        [ 1.0754, -0.4700, -0.8900],
        [ 0.1029,  0.1087,  0.3508],
        [ 0.1336,  2.5423,  1.5134],
        [ 1.2471, -0.0053, -0.3461]])
tensor([[-0.3004,  1.0754,  0.1029,  0.1336,  1.2471],
        [ 0.1901, -0.4700,  0.1087,  2.5423, -0.0053],
        [ 2.3058, -0.8900,  0.3508,  1.5134, -0.3461]])


Explanation about example:
- The above function transposed the tensor of size [5,3] to a tensor of size [3,5]. 1,0  in the above example denotes that they'd be transposed.

In [53]:
# Example 3 - breaking (to illustrate when it breaks)
tran2 = torch.transpose(tt1,1, 2)

IndexError: ignored

Explanation about example:
 - Dimensions for the transpose were out of range. Expecting to get the 0,1 or 1,2 but got different numbers which were out of range.

Closing comments about when to use this function:
 - transpose function is very helpful when you want to do matrix multiplication of tensors with same shape( matrix multiplication is not possible on matrices with same shape), hence the transpose of them is required.

In [54]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aayrm5/01-tensor-operations


'https://jovian.ai/aayrm5/01-tensor-operations'

## Conclusion

The functions discussed are one of the important ones while doing tensor operations. 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html


In [55]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aayrm5/01-tensor-operations


'https://jovian.ai/aayrm5/01-tensor-operations'

In [57]:
jovian.submit(project='01-tensor-operations',assignment="zerotogans-a1")

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aayrm5/01-tensor-operations
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor
